import { motion } from 'framer-motion';
import { toast } from 'sonner';
import {
  FileText, FileBarChart, UserCheck, Building2,
  Download, Share2, Calendar, Sparkles,
} from 'lucide-react';

const REPORT_CARDS = [
  {
    id: 'weekly',
    icon: FileText,
    title: 'Weekly Summary Report',
    subtitle: 'District-wide health overview',
    lastGenerated: 'Today, 06:00 AM',
    type: 'PDF',
    color: 'blue',
    canShare: false,
  },
  {
    id: 'medicine',
    icon: FileBarChart,
    title: 'Monthly Medicine Report',
    subtitle: 'Consumption & procurement data',
    lastGenerated: 'Jul 1, 2025',
    type: 'CSV',
    color: 'purple',
    canShare: false,
  },
  {
    id: 'doctor',
    icon: UserCheck,
    title: 'Doctor Attendance Report',
    subtitle: 'Daily & monthly attendance logs',
    lastGenerated: 'Today, 08:00 AM',
    type: 'PDF',
    color: 'green',
    canShare: false,
  },
  {
    id: 'phc',
    icon: Building2,
    title: 'PHC Performance Report',
    subtitle: 'KPIs across all 5 centers',
    lastGenerated: 'Jul 5, 2025',
    type: 'PDF',
    color: 'orange',
    canShare: true,
  },
];

const COLOR_MAP: Record<string, { bg: string; icon: string; btn: string }> = {
  blue:   { bg: 'bg-blue-50',   icon: 'text-blue-600',   btn: 'bg-blue-600 hover:bg-blue-700 text-white' },
  purple: { bg: 'bg-purple-50', icon: 'text-purple-600', btn: 'bg-purple-600 hover:bg-purple-700 text-white' },
  green:  { bg: 'bg-green-50',  icon: 'text-green-600',  btn: 'bg-green-600 hover:bg-green-700 text-white' },
  orange: { bg: 'bg-orange-50', icon: 'text-orange-600', btn: 'bg-orange-600 hover:bg-orange-700 text-white' },
};

function handleDownload(title: string, type: string) {
  toast.info(`Generating ${type} report...`, {
    description: `${title} — AI is compiling data (simulated)`,
    duration: 3000,
  });
}

export default function AdminReports() {
  return (
    <div className="p-5 space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-base font-bold text-gray-900">Reports &amp; Exports</h1>
          <p className="text-xs text-gray-500 mt-0.5">Auto-generated by AI · NHM Erode District</p>
        </div>
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-600 text-xs font-medium rounded-lg transition-colors">
            <Calendar className="w-3.5 h-3.5" />
            Filter by Date
          </button>
        </div>
      </div>

      {/* Report Cards Grid */}
      <div className="grid grid-cols-2 gap-4">
        {REPORT_CARDS.map((card, i) => {
          const c = COLOR_MAP[card.color];
          const Icon = card.icon;
          return (
            <motion.div
              key={card.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07 }}
              className="bg-white rounded-xl border border-gray-100 p-4 shadow-sm"
            >
              <div className="flex items-start justify-between mb-3">
                <div className={`w-9 h-9 rounded-lg ${c.bg} flex items-center justify-center`}>
                  <Icon className={`w-4.5 h-4.5 ${c.icon}`} />
                </div>
                <span className="flex items-center gap-1 text-[10px] text-gray-400 bg-gray-50 px-2 py-0.5 rounded-full border border-gray-100">
                  <Sparkles className="w-2.5 h-2.5 text-purple-400" />
                  Auto-generated by AI
                </span>
              </div>

              <h3 className="font-bold text-sm text-gray-900">{card.title}</h3>
              <p className="text-[11px] text-gray-500 mt-0.5">{card.subtitle}</p>

              <div className="flex items-center gap-1 mt-2">
                <Calendar className="w-3 h-3 text-gray-400" />
                <span className="text-[10px] text-gray-400">Last generated: {card.lastGenerated}</span>
              </div>

              <div className="flex gap-2 mt-3">
                <button
                  onClick={() => handleDownload(card.title, card.type)}
                  className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors ${c.btn}`}
                >
                  <Download className="w-3 h-3" />
                  {card.type} Download
                </button>
                {card.canShare && (
                  <button
                    onClick={() => toast.success('Share link copied!', { description: 'Report link copied to clipboard (simulated)' })}
                    className="flex items-center gap-1 px-3 py-1.5 border border-gray-200 hover:bg-gray-50 text-gray-600 text-xs font-medium rounded-lg transition-colors"
                  >
                    <Share2 className="w-3 h-3" />
                    Share
                  </button>
                )}
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Report Preview */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        {/* GOI-style header */}
        <div className="bg-[#0B6CBB] p-5 text-white">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-widest text-blue-200 mb-1">
                National Health Mission · Government of India
              </p>
              <h2 className="text-base font-bold">Weekly District Health Report</h2>
              <p className="text-xs text-blue-200 mt-0.5">Erode District, Tamil Nadu</p>
            </div>
            <div className="text-right">
              <p className="text-[10px] text-blue-200">Report Period</p>
              <p className="text-xs font-semibold">Jun 30 – Jul 6, 2025</p>
              <p className="text-[10px] text-blue-300 mt-1">Generated: Jul 6, 2025 06:00 AM</p>
            </div>
          </div>
        </div>

        <div className="p-6 space-y-5">
          {/* Executive Summary */}
          <section>
            <h3 className="font-bold text-xs text-gray-800 uppercase tracking-wide border-b border-gray-100 pb-1.5 mb-2">
              Executive Summary
            </h3>
            <p className="text-xs text-gray-700 leading-relaxed">
              This week, the Erode District recorded a total of <strong>3,964 patient consultations</strong> across 5 health
              centres (1 CHC, 4 PHCs). PHC-Alpha continues to operate under critical stress with bed occupancy at
              100% and only 1 of 3 doctors present. AI systems have flagged 5 high-priority actions, of which 2
              involve critical medicine stock-outs requiring immediate district-level intervention.
            </p>
          </section>

          {/* Key Findings */}
          <section>
            <h3 className="font-bold text-xs text-gray-800 uppercase tracking-wide border-b border-gray-100 pb-1.5 mb-3">
              Key Findings
            </h3>
            <ul className="space-y-2.5">
              {[
                {
                  color: 'red',
                  text: 'PHC-Alpha is in CRITICAL status — 100% bed occupancy, 33% doctor attendance, and 2 medicines at zero stock (Paracetamol, ORS Sachets). Immediate resource mobilization required.',
                },
                {
                  color: 'orange',
                  text: 'AI detected a dengue cluster in Karungal ward (14 cases, 78% outbreak probability). Vector control deployment recommended within 24 hours.',
                },
                {
                  color: 'blue',
                  text: 'CHC-Central maintains surplus stock of Paracetamol (5,000 units) and ORS (1,500 packs), suitable for redistribution to critical centers.',
                },
              ].map((item, i) => (
                <li key={i} className={`flex gap-2.5 text-xs text-gray-700`}>
                  <div className={`mt-1 w-2 h-2 rounded-full shrink-0 ${item.color === 'red' ? 'bg-red-500' : item.color === 'orange' ? 'bg-orange-400' : 'bg-blue-500'}`} />
                  <span className="leading-relaxed">{item.text}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Recommendations */}
          <section>
            <h3 className="font-bold text-xs text-gray-800 uppercase tracking-wide border-b border-gray-100 pb-1.5 mb-3">
              Recommendations
            </h3>
            <div className="bg-blue-50 rounded-lg p-3 border border-blue-100">
              <ol className="space-y-1.5 text-xs text-blue-900">
                {[
                  'Immediately transfer 500 Paracetamol tablets and 200 ORS sachets from CHC-Central to PHC-Alpha.',
                  'Temporarily reassign Dr. Meena from PHC-North to PHC-Alpha given differential patient load.',
                  'Initiate dengue rapid testing protocol in Karungal ward; coordinate with district vector control for fogging.',
                  'Schedule emergency PHC-Alpha infrastructure review with district health officer.',
                ].map((rec, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="font-bold text-blue-600 shrink-0">{i + 1}.</span>
                    <span className="leading-relaxed">{rec}</span>
                  </li>
                ))}
              </ol>
            </div>
          </section>

          {/* Signatures */}
          <section className="pt-4 border-t border-gray-100">
            <div className="grid grid-cols-3 gap-6">
              {['District Health Officer', 'NHM Programme Manager', 'Data Quality Officer'].map(role => (
                <div key={role} className="text-center">
                  <div className="border-b border-gray-300 mb-1.5 h-8" />
                  <p className="text-[10px] font-semibold text-gray-700">{role}</p>
                  <p className="text-[9px] text-gray-400">Erode District, TN</p>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
