import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { COLORS } from '@/lib/data';

const REPORTS = [
  { id:'weekly',   icon:'document-text', title:'Weekly Summary',      sub:'District health overview',        color:'#3b82f6', type:'PDF', date:'Today 06:00 AM' },
  { id:'medicine', icon:'cube',          title:'Medicine Report',      sub:'Consumption & procurement data',  color:'#7c3aed', type:'CSV', date:'Jul 1, 2025'     },
  { id:'doctor',   icon:'person-circle', title:'Attendance Report',    sub:'Daily & monthly attendance logs', color:COLORS.green, type:'PDF', date:'Today 08:00 AM' },
  { id:'phc',      icon:'business',      title:'PHC Performance',      sub:'KPIs across all 5 centres',       color:COLORS.orange, type:'PDF', date:'Jul 5, 2025'   },
];

export default function AdminReports() {
  return (
    <ScrollView style={{ flex:1, backgroundColor:COLORS.bg }} contentContainerStyle={{ padding:14, paddingTop:60 }} showsVerticalScrollIndicator={false}>
      <Text style={styles.pageTitle}>Reports &amp; Exports</Text>
      <Text style={styles.pageSub}>Auto-generated by AI · NHM Erode District</Text>

      {REPORTS.map(r => (
        <View key={r.id} style={[styles.card, { borderLeftColor:r.color, borderLeftWidth:4 }]}>
          <View style={{ flexDirection:'row', alignItems:'flex-start', gap:12 }}>
            <View style={[styles.iconBox, { backgroundColor:r.color+'15' }]}>
              <Ionicons name={r.icon as any} size={22} color={r.color} />
            </View>
            <View style={{ flex:1 }}>
              <View style={{ flexDirection:'row', alignItems:'center', gap:6, marginBottom:3, flexWrap:'wrap' }}>
                <Text style={styles.cardTitle}>{r.title}</Text>
                <View style={styles.aiBadge}>
                  <Ionicons name="sparkles" size={9} color="#7c3aed" />
                  <Text style={styles.aiText}>AI generated</Text>
                </View>
              </View>
              <Text style={styles.cardSub}>{r.sub}</Text>
              <View style={{ flexDirection:'row', alignItems:'center', gap:4, marginTop:5 }}>
                <Ionicons name="calendar-outline" size={10} color={COLORS.textSub} />
                <Text style={styles.dateText}>Last generated: {r.date}</Text>
              </View>
            </View>
          </View>
          <View style={styles.btnRow}>
            <TouchableOpacity
              onPress={() => Alert.alert(`Generating ${r.type}`, `${r.title} — AI is compiling district data (simulated)`)}
              style={[styles.downloadBtn, { backgroundColor:r.color }]}
            >
              <Ionicons name="download-outline" size={14} color="#fff" />
              <Text style={styles.downloadText}>Download {r.type}</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => Alert.alert('Shared!', 'Report link copied to clipboard (simulated)')}
              style={styles.shareBtn}
            >
              <Ionicons name="share-outline" size={14} color={COLORS.textSub} />
            </TouchableOpacity>
          </View>
        </View>
      ))}

      {/* GOI Report Preview */}
      <View style={styles.govReport}>
        <View style={styles.govHeader}>
          <Text style={styles.govBanner}>NATIONAL HEALTH MISSION · GOVT. OF INDIA</Text>
          <Text style={styles.govTitle}>Weekly District Health Report</Text>
          <Text style={styles.govSub}>Erode District, Tamil Nadu · Jun 30 – Jul 6, 2025</Text>
        </View>
        <View style={{ padding:16 }}>
          <Text style={styles.govSection}>Executive Summary</Text>
          <Text style={styles.govBody}>
            This week, Erode District recorded <Text style={{ fontWeight:'700' }}>3,964 consultations</Text> across 5 health centres. PHC-Alpha is in critical status with 100% bed occupancy and only 1/3 doctors present. AI has flagged 5 high-priority actions.
          </Text>
          <Text style={styles.govSection}>Key Findings</Text>
          {[
            { color:COLORS.red,    text:'PHC-Alpha at 100% bed occupancy. 2 medicines at zero stock. Immediate intervention needed.' },
            { color:COLORS.orange, text:'Dengue cluster detected in Karungal ward. 14 cases, 78% outbreak probability.' },
            { color:'#3b82f6',     text:'CHC-Central has surplus: 5,000 Paracetamol, 1,500 ORS — ready for redistribution.' },
          ].map((f,i) => (
            <View key={i} style={{ flexDirection:'row', gap:8, marginBottom:8 }}>
              <View style={{ width:6, height:6, borderRadius:3, backgroundColor:f.color, marginTop:5 }} />
              <Text style={styles.govBody}>{f.text}</Text>
            </View>
          ))}
          <View style={styles.sigRow}>
            {['District Health Officer','NHM Programme Manager','Data Quality Officer'].map(s => (
              <View key={s} style={styles.sigBox}>
                <View style={styles.sigLine} />
                <Text style={styles.sigName}>{s}</Text>
              </View>
            ))}
          </View>
        </View>
      </View>
      <View style={{ height:20 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  pageTitle: { fontSize:17, fontWeight:'900', color:COLORS.text },
  pageSub: { fontSize:11, color:COLORS.textSub, marginTop:3, marginBottom:16 },
  card: { backgroundColor:'#fff', borderRadius:16, padding:14, marginBottom:12, borderWidth:1, borderColor:COLORS.border },
  iconBox: { width:44, height:44, borderRadius:14, alignItems:'center', justifyContent:'center' },
  cardTitle: { fontSize:13, fontWeight:'800', color:COLORS.text },
  aiBadge: { flexDirection:'row', alignItems:'center', gap:3, backgroundColor:'#ede9fe', borderRadius:100, paddingHorizontal:7, paddingVertical:2 },
  aiText: { fontSize:9, color:'#7c3aed', fontWeight:'700' },
  cardSub: { fontSize:11, color:COLORS.textSub },
  dateText: { fontSize:10, color:COLORS.textSub },
  btnRow: { flexDirection:'row', gap:8, marginTop:12 },
  downloadBtn: { flex:1, flexDirection:'row', alignItems:'center', justifyContent:'center', gap:6, borderRadius:12, paddingVertical:11 },
  downloadText: { color:'#fff', fontSize:12, fontWeight:'700' },
  shareBtn: { width:42, height:42, borderRadius:12, backgroundColor:'#f1f5f9', alignItems:'center', justifyContent:'center', borderWidth:1, borderColor:COLORS.border },
  govReport: { backgroundColor:'#fff', borderRadius:16, borderWidth:1, borderColor:COLORS.border, overflow:'hidden', marginBottom:14 },
  govHeader: { backgroundColor:COLORS.primary, padding:16 },
  govBanner: { color:'rgba(255,255,255,.6)', fontSize:8, fontWeight:'700', letterSpacing:1.5, textTransform:'uppercase', marginBottom:6 },
  govTitle: { color:'#fff', fontSize:15, fontWeight:'900' },
  govSub: { color:'rgba(255,255,255,.7)', fontSize:11, marginTop:3 },
  govSection: { fontSize:11, fontWeight:'800', color:COLORS.text, textTransform:'uppercase', letterSpacing:.5, borderBottomWidth:1, borderBottomColor:COLORS.border, paddingBottom:6, marginBottom:10, marginTop:12 },
  govBody: { fontSize:12, color:COLORS.textSub, lineHeight:18, flex:1 },
  sigRow: { flexDirection:'row', gap:12, marginTop:20, paddingTop:16, borderTopWidth:1, borderTopColor:COLORS.border },
  sigBox: { flex:1, alignItems:'center' },
  sigLine: { width:'100%', height:1, backgroundColor:COLORS.border, marginBottom:6 },
  sigName: { fontSize:8, color:COLORS.textSub, textAlign:'center', lineHeight:13 },
});
